# nginx proxy address - http://172.17.0.1:50001

name: ifconfig
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: 'casjaysdevdocker/ifconfig:latest'
    container_name: ifconfig-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    tty: true
    stdin_open: true
    privileged: true
    logging: *default-logging
    environment:
      - TZ=${TZ:-America/New_York}
      - CONTAINER_PROTOCOL=http
      - CONTAINER_NAME="ifconfig-app"
      - CONTAINER_WEB_SERVER_PROTOCOL=http
      - HOSTNAME=${BASE_HOST_NAME:-$HOSTNAME}
      - DOMAINNAME=${BASE_DOMAIN_NAME:-$HOSTNAME}
      - CURRENT_IP_4="${CURRENT_IP_4:-}"
      - CURRENT_IP_6="${CURRENT_IP_6:-}"
    ports:
      - '172.17.0.1:50001:80'
    volumes:
      - './rootfs/data/ifconfig:/data:z'
      - './rootfs/config/ifconfig:/config:z'
    networks:
      - ifconfig

networks:
  ifconfig:
    name: ifconfig
    external: false
